package com.application.cool.history.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.application.cool.history.db.PersonEntity;
import com.application.cool.history.db.EventEntity;
import com.application.cool.history.db.PostEntity;

import com.application.cool.history.db.PersonEntityDao;
import com.application.cool.history.db.EventEntityDao;
import com.application.cool.history.db.PostEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personEntityDaoConfig;
    private final DaoConfig eventEntityDaoConfig;
    private final DaoConfig postEntityDaoConfig;

    private final PersonEntityDao personEntityDao;
    private final EventEntityDao eventEntityDao;
    private final PostEntityDao postEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personEntityDaoConfig = daoConfigMap.get(PersonEntityDao.class).clone();
        personEntityDaoConfig.initIdentityScope(type);

        eventEntityDaoConfig = daoConfigMap.get(EventEntityDao.class).clone();
        eventEntityDaoConfig.initIdentityScope(type);

        postEntityDaoConfig = daoConfigMap.get(PostEntityDao.class).clone();
        postEntityDaoConfig.initIdentityScope(type);

        personEntityDao = new PersonEntityDao(personEntityDaoConfig, this);
        eventEntityDao = new EventEntityDao(eventEntityDaoConfig, this);
        postEntityDao = new PostEntityDao(postEntityDaoConfig, this);

        registerDao(PersonEntity.class, personEntityDao);
        registerDao(EventEntity.class, eventEntityDao);
        registerDao(PostEntity.class, postEntityDao);
    }
    
    public void clear() {
        personEntityDaoConfig.clearIdentityScope();
        eventEntityDaoConfig.clearIdentityScope();
        postEntityDaoConfig.clearIdentityScope();
    }

    public PersonEntityDao getPersonEntityDao() {
        return personEntityDao;
    }

    public EventEntityDao getEventEntityDao() {
        return eventEntityDao;
    }

    public PostEntityDao getPostEntityDao() {
        return postEntityDao;
    }

}
