package com.application.cool.history.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.application.cool.history.db.Person;
import com.application.cool.history.db.Event;

import com.application.cool.history.db.PersonDao;
import com.application.cool.history.db.EventDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personDaoConfig;
    private final DaoConfig eventDaoConfig;

    private final PersonDao personDao;
    private final EventDao eventDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        eventDaoConfig = daoConfigMap.get(EventDao.class).clone();
        eventDaoConfig.initIdentityScope(type);

        personDao = new PersonDao(personDaoConfig, this);
        eventDao = new EventDao(eventDaoConfig, this);

        registerDao(Person.class, personDao);
        registerDao(Event.class, eventDao);
    }
    
    public void clear() {
        personDaoConfig.clearIdentityScope();
        eventDaoConfig.clearIdentityScope();
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

    public EventDao getEventDao() {
        return eventDao;
    }

}
