package com.application.cool.history.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "EVENT_ENTITY".
 */
@Entity
public class EventEntity {

    @Id
    @NotNull
    private String eventId;
    private String avatarURL;
    private String infoURL;
    private String name;
    private String type;
    private Integer start;
    private Integer end;
    private String dynasty;
    private String dynastyDetail;
    private String pinyin;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public EventEntity() {
    }

    public EventEntity(String eventId) {
        this.eventId = eventId;
    }

    @Generated
    public EventEntity(String eventId, String avatarURL, String infoURL, String name, String type, Integer start, Integer end, String dynasty, String dynastyDetail, String pinyin) {
        this.eventId = eventId;
        this.avatarURL = avatarURL;
        this.infoURL = infoURL;
        this.name = name;
        this.type = type;
        this.start = start;
        this.end = end;
        this.dynasty = dynasty;
        this.dynastyDetail = dynastyDetail;
        this.pinyin = pinyin;
    }

    @NotNull
    public String getEventId() {
        return eventId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEventId(@NotNull String eventId) {
        this.eventId = eventId;
    }

    public String getAvatarURL() {
        return avatarURL;
    }

    public void setAvatarURL(String avatarURL) {
        this.avatarURL = avatarURL;
    }

    public String getInfoURL() {
        return infoURL;
    }

    public void setInfoURL(String infoURL) {
        this.infoURL = infoURL;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getStart() {
        return start;
    }

    public void setStart(Integer start) {
        this.start = start;
    }

    public Integer getEnd() {
        return end;
    }

    public void setEnd(Integer end) {
        this.end = end;
    }

    public String getDynasty() {
        return dynasty;
    }

    public void setDynasty(String dynasty) {
        this.dynasty = dynasty;
    }

    public String getDynastyDetail() {
        return dynastyDetail;
    }

    public void setDynastyDetail(String dynastyDetail) {
        this.dynastyDetail = dynastyDetail;
    }

    public String getPinyin() {
        return pinyin;
    }

    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
