package com.application.cool.history.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EVENT_ENTITY".
*/
public class EventEntityDao extends AbstractDao<EventEntity, String> {

    public static final String TABLENAME = "EVENT_ENTITY";

    /**
     * Properties of entity EventEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property EventId = new Property(0, String.class, "eventId", true, "EVENT_ID");
        public final static Property AvatarURL = new Property(1, String.class, "avatarURL", false, "AVATAR_URL");
        public final static Property InfoURL = new Property(2, String.class, "infoURL", false, "INFO_URL");
        public final static Property Name = new Property(3, String.class, "name", false, "NAME");
        public final static Property Type = new Property(4, String.class, "type", false, "TYPE");
        public final static Property Start = new Property(5, Integer.class, "start", false, "START");
        public final static Property End = new Property(6, Integer.class, "end", false, "END");
        public final static Property Dynasty = new Property(7, String.class, "dynasty", false, "DYNASTY");
        public final static Property DynastyDetail = new Property(8, String.class, "dynastyDetail", false, "DYNASTY_DETAIL");
        public final static Property Pinyin = new Property(9, String.class, "pinyin", false, "PINYIN");
    }


    public EventEntityDao(DaoConfig config) {
        super(config);
    }
    
    public EventEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EVENT_ENTITY\" (" + //
                "\"EVENT_ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: eventId
                "\"AVATAR_URL\" TEXT," + // 1: avatarURL
                "\"INFO_URL\" TEXT," + // 2: infoURL
                "\"NAME\" TEXT," + // 3: name
                "\"TYPE\" TEXT," + // 4: type
                "\"START\" INTEGER," + // 5: start
                "\"END\" INTEGER," + // 6: end
                "\"DYNASTY\" TEXT," + // 7: dynasty
                "\"DYNASTY_DETAIL\" TEXT," + // 8: dynastyDetail
                "\"PINYIN\" TEXT);"); // 9: pinyin
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EVENT_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, EventEntity entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getEventId());
 
        String avatarURL = entity.getAvatarURL();
        if (avatarURL != null) {
            stmt.bindString(2, avatarURL);
        }
 
        String infoURL = entity.getInfoURL();
        if (infoURL != null) {
            stmt.bindString(3, infoURL);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(5, type);
        }
 
        Integer start = entity.getStart();
        if (start != null) {
            stmt.bindLong(6, start);
        }
 
        Integer end = entity.getEnd();
        if (end != null) {
            stmt.bindLong(7, end);
        }
 
        String dynasty = entity.getDynasty();
        if (dynasty != null) {
            stmt.bindString(8, dynasty);
        }
 
        String dynastyDetail = entity.getDynastyDetail();
        if (dynastyDetail != null) {
            stmt.bindString(9, dynastyDetail);
        }
 
        String pinyin = entity.getPinyin();
        if (pinyin != null) {
            stmt.bindString(10, pinyin);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, EventEntity entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getEventId());
 
        String avatarURL = entity.getAvatarURL();
        if (avatarURL != null) {
            stmt.bindString(2, avatarURL);
        }
 
        String infoURL = entity.getInfoURL();
        if (infoURL != null) {
            stmt.bindString(3, infoURL);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(5, type);
        }
 
        Integer start = entity.getStart();
        if (start != null) {
            stmt.bindLong(6, start);
        }
 
        Integer end = entity.getEnd();
        if (end != null) {
            stmt.bindLong(7, end);
        }
 
        String dynasty = entity.getDynasty();
        if (dynasty != null) {
            stmt.bindString(8, dynasty);
        }
 
        String dynastyDetail = entity.getDynastyDetail();
        if (dynastyDetail != null) {
            stmt.bindString(9, dynastyDetail);
        }
 
        String pinyin = entity.getPinyin();
        if (pinyin != null) {
            stmt.bindString(10, pinyin);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    @Override
    public EventEntity readEntity(Cursor cursor, int offset) {
        EventEntity entity = new EventEntity( //
            cursor.getString(offset + 0), // eventId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // avatarURL
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // infoURL
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // name
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // type
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // start
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // end
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // dynasty
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // dynastyDetail
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9) // pinyin
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, EventEntity entity, int offset) {
        entity.setEventId(cursor.getString(offset + 0));
        entity.setAvatarURL(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setInfoURL(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setType(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setStart(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setEnd(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setDynasty(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setDynastyDetail(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setPinyin(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
     }
    
    @Override
    protected final String updateKeyAfterInsert(EventEntity entity, long rowId) {
        return entity.getEventId();
    }
    
    @Override
    public String getKey(EventEntity entity) {
        if(entity != null) {
            return entity.getEventId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(EventEntity entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
