package com.application.cool.history.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "PERSON".
 */
@Entity
public class Person {

    @Id
    private int person_id;
    private String avatar_url;
    private String info_url;
    private String name;
    private String type;
    private Integer start;
    private Integer end;
    private String dynasty;
    private String dynasty_detail;
    private String pinyin;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated(hash = 1024547259)
    public Person() {
    }

    public Person(int person_id) {
        this.person_id = person_id;
    }

    @Generated(hash = 2060632992)
    public Person(int person_id, String avatar_url, String info_url, String name, String type, Integer start, Integer end, String dynasty, String dynasty_detail, String pinyin) {
        this.person_id = person_id;
        this.avatar_url = avatar_url;
        this.info_url = info_url;
        this.name = name;
        this.type = type;
        this.start = start;
        this.end = end;
        this.dynasty = dynasty;
        this.dynasty_detail = dynasty_detail;
        this.pinyin = pinyin;
    }

    public int getPerson_id() {
        return person_id;
    }

    public void setPerson_id(int person_id) {
        this.person_id = person_id;
    }

    public String getAvatar_url() {
        return avatar_url;
    }

    public void setAvatar_url(String avatar_url) {
        this.avatar_url = avatar_url;
    }

    public String getInfo_url() {
        return info_url;
    }

    public void setInfo_url(String info_url) {
        this.info_url = info_url;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getStart() {
        return start;
    }

    public void setStart(Integer start) {
        this.start = start;
    }

    public Integer getEnd() {
        return end;
    }

    public void setEnd(Integer end) {
        this.end = end;
    }

    public String getDynasty() {
        return dynasty;
    }

    public void setDynasty(String dynasty) {
        this.dynasty = dynasty;
    }

    public String getDynasty_detail() {
        return dynasty_detail;
    }

    public void setDynasty_detail(String dynasty_detail) {
        this.dynasty_detail = dynasty_detail;
    }

    public String getPinyin() {
        return pinyin;
    }

    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
