package com.application.cool.history.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "POST_ENTITY".
 */
@Entity
public class PostEntity {

    @Id
    @NotNull
    private String postId;
    private String imageURL;
    private String textURL;
    private String title;
    private String type;
    private String authorId;
    private String dynasty;
    private String topic;
    private String subtopic;
    private Integer likes;
    private Integer dislikes;
    private Integer subscribers;
    private Integer replies;
    private Integer reviews;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public PostEntity() {
    }

    public PostEntity(String postId) {
        this.postId = postId;
    }

    @Generated
    public PostEntity(String postId, String imageURL, String textURL, String title, String type, String authorId, String dynasty, String topic, String subtopic, Integer likes, Integer dislikes, Integer subscribers, Integer replies, Integer reviews) {
        this.postId = postId;
        this.imageURL = imageURL;
        this.textURL = textURL;
        this.title = title;
        this.type = type;
        this.authorId = authorId;
        this.dynasty = dynasty;
        this.topic = topic;
        this.subtopic = subtopic;
        this.likes = likes;
        this.dislikes = dislikes;
        this.subscribers = subscribers;
        this.replies = replies;
        this.reviews = reviews;
    }

    @NotNull
    public String getPostId() {
        return postId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPostId(@NotNull String postId) {
        this.postId = postId;
    }

    public String getImageURL() {
        return imageURL;
    }

    public void setImageURL(String imageURL) {
        this.imageURL = imageURL;
    }

    public String getTextURL() {
        return textURL;
    }

    public void setTextURL(String textURL) {
        this.textURL = textURL;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getAuthorId() {
        return authorId;
    }

    public void setAuthorId(String authorId) {
        this.authorId = authorId;
    }

    public String getDynasty() {
        return dynasty;
    }

    public void setDynasty(String dynasty) {
        this.dynasty = dynasty;
    }

    public String getTopic() {
        return topic;
    }

    public void setTopic(String topic) {
        this.topic = topic;
    }

    public String getSubtopic() {
        return subtopic;
    }

    public void setSubtopic(String subtopic) {
        this.subtopic = subtopic;
    }

    public Integer getLikes() {
        return likes;
    }

    public void setLikes(Integer likes) {
        this.likes = likes;
    }

    public Integer getDislikes() {
        return dislikes;
    }

    public void setDislikes(Integer dislikes) {
        this.dislikes = dislikes;
    }

    public Integer getSubscribers() {
        return subscribers;
    }

    public void setSubscribers(Integer subscribers) {
        this.subscribers = subscribers;
    }

    public Integer getReplies() {
        return replies;
    }

    public void setReplies(Integer replies) {
        this.replies = replies;
    }

    public Integer getReviews() {
        return reviews;
    }

    public void setReviews(Integer reviews) {
        this.reviews = reviews;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
